CREATE DATABASE recipes_db;

USE recipes_db;

CREATE TABLE users (
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
username VARCHAR(20) NOT NULL,
password CHAR(60) NOT NULL,
fullName VARCHAR(60) NOT NULL,
PRIMARY KEY (id),
INDEX id_UNIQUE (id ASC),
INDEX username_UNIQUE (username ASC)
);

CREATE TABLE recipes (
id INT NOT NULL AUTO_INCREMENT,
userID INT NOT NULL,
recipeName VARCHAR(200) NOT NULL,
recipeImage VARCHAR(200) NOT NULL,
recipeurl VARCHAR(200) NOT NULL,
calories INT NOT NULL,
dietLabels VARCHAR(200) NOT NULL,
healthLabels VARCHAR(200) NOT NULL,
ingredientLines VARCHAR(1000) NOT NULL,
yield INT NOT NULL,
createdAt DATETIME,
updatedAt DATETIME,
PRIMARY KEY (id)
);

CREATE TABLE trackers (
id INT NOT NULL AUTO_INCREMENT,
userID INT,
calories INT DEFAULT 0,
fat INT DEFAULT 0,
cholesterol INT DEFAULT 0,
sodium INT DEFAULT 0,
carbs INT DEFAULT 0,
sugar INT DEFAULT 0,
protein INT DEFAULT 0,
createdAt DATETIME DEFAULT 0,
updatedAt DATETIME DEFAULT 0,
PRIMARY KEY (id)
);
